spring.application.name=finplus

# URL de conexão
spring.datasource.url=jdbc:postgresql://localhost:5432/finplus

# Usuário
spring.datasource.username=${PGSQL_USERNAME}

# Senha
spring.datasource.password=${PGSQL_PASSWORD}

# Driver do PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
# O dialeto ajuda o Hibernate a falar a "língua" específica do Postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ddl-auto: 'update' cria as tabelas automaticamente se elas não existirem,
# ou altera se você adicionar novas colunas (mas não deleta dados existentes).
spring.jpa.hibernate.ddl-auto=update

# Mostra o SQL gerado pelo Spring no console (ótimo para testar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true